
package com.dbs.schemas.my.wsdl.test._1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-22T11:27:28.184+08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "DetailInfo", targetNamespace = "http://schemas.dbs.com/my/common/1_1")
public class Fault extends Exception {
    
    private com.dbs.schemas.my.common._1_1.DetailInfo detailInfo;

    public Fault() {
        super();
    }
    
    public Fault(String message) {
        super(message);
    }
    
    public Fault(String message, Throwable cause) {
        super(message, cause);
    }

    public Fault(String message, com.dbs.schemas.my.common._1_1.DetailInfo detailInfo) {
        super(message);
        this.detailInfo = detailInfo;
    }

    public Fault(String message, com.dbs.schemas.my.common._1_1.DetailInfo detailInfo, Throwable cause) {
        super(message, cause);
        this.detailInfo = detailInfo;
    }

    public com.dbs.schemas.my.common._1_1.DetailInfo getFaultInfo() {
        return this.detailInfo;
    }
}
