DROP TABLE IF EXISTS `SEQ_TABLE`;
CREATE TABLE `SEQ_TABLE` (
  `SEQ_NAME` varchar(50) NOT NULL,
  `CURRENT_VALUE` bigint(20) NOT NULL DEFAULT '1000000002',
  `INCREMENT` smallint(6) NOT NULL DEFAULT '1',
  `REMARK` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`SEQ_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `SEQ_TABLE` VALUES ('ACCOUNT_NO_SEQ',100001081,1,'账户--账户编号');