
DROP FUNCTION IF EXISTS `FUN_DATE_ADD`;
DROP FUNCTION IF EXISTS `FUN_NOW`;
DROP FUNCTION IF EXISTS `FUN_SEQ`;
DROP FUNCTION IF EXISTS `FUN_SEQ_CURRENT_VALUE`;


DELIMITER $$
CREATE FUNCTION `FUN_DATE_ADD`(STR_DATE VARCHAR(10), STR_INTERVAL bigint(20)) RETURNS date
BEGIN
	RETURN date_add(STR_DATE, INTERVAL STR_INTERVAL DAY);
END;
$$
DELIMITER ;


DELIMITER $$
CREATE FUNCTION `FUN_NOW`() RETURNS datetime
BEGIN
	RETURN now();
END;
$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION `FUN_SEQ`(SEQ VARCHAR(50)) RETURNS bigint(20)
BEGIN
     UPDATE SEQ_TABLE
     SET CURRENT_VALUE = CURRENT_VALUE + INCREMENT
     WHERE  SEQ_NAME=SEQ;
     RETURN FUN_SEQ_CURRENT_VALUE(SEQ);
END;
$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION `FUN_SEQ_CURRENT_VALUE`(SEQ VARCHAR(50)) RETURNS bigint(20)
BEGIN
    DECLARE VALUE INTEGER;
    SET VALUE=0;
    SELECT CURRENT_VALUE INTO VALUE
    FROM SEQ_TABLE
    WHERE SEQ_NAME=SEQ;
    RETURN VALUE;
END;
$$
DELIMITER ;